apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: 2-service-redis # Label selector to target your Redis pod
  ports:
    - protocol: TCP
      port: 6379 # Port on which Redis is listening